[[members]]
name = "Johnny Willer"
level = 1

[[members]]
name = "Alexandros Lioumbis"
level = 2

[[members]]
name = "Antonio Sanicola"
level = 5

[[members]]
name = "Bohdan Chumadin"
level = 2

[[members]]
name = "Ewelina Grzebielucha"
level = 1

[[members]]
name = "Janine de la Fuente"
level = 5

[[members]]
name = "Karla Carus"
level = 4

[[members]]
name = "Lara Kocbek"
level = 1

[[members]]
name = "Lukas Kosnar"
level = 2

[[members]]
name = "Marcin Ibrom"
level = 4

[[members]]
name = "Maria Kelly"
level = 5

[[members]]
name = "Marie-Pierre Coutart"
level = 3

[[members]]
name = "Nabeelah Yousuph"
level = 2

[[members]]
name = "Padraic Cunningham"
level = 4

[[members]]
name = "Tatiana Bekisheva"
level = 3

[[members]]
name = "Venus O'Hara"
level = 5
